Got stuck because of S.foldMap issue
foldMap :: (Monoid m, Foldable f) => TypeRep m -> (a -> m) -> f a -> m

Why does the following work:
> S.foldMap (String) (b => b === true ? 'yes' : 'no') ([true, true, false])
'yesyesno'

But not:
> S.foldMap (Boolean) (b => b === true) ([true, true, false])
Uncaught TypeError: Monoid.methods.empty(...) is not a function
    at empty (node_modules/sanctuary-type-classes/index.js:1438:43)
    at foldMap (node_modules/sanctuary-type-classes/index.js:2094:20)

or:

> S.foldMap (Boolean) (b => b === 'y') (['y','y','n'])
Uncaught TypeError: Monoid.methods.empty(...) is not a function

Is it `Boolean` that is wrong?
> S.foldMap (String) (b => b === 'y' ? 'yes' : 'no') (['y','y','n'])
'yesyesno'